version: '3.3'

services:
  maria-db:
    image: mariadb:10.4.8
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_DATABASE: remembrall
      MYSQL_USER: remembrall
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - maria-db-storage:/var/lib/mysql

  redis:
    image: redis:6.0.5
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  maria-db-storage: