version: '3.3'

services:
  remembrall:
    image: remembrall/remembrall
    ports:
      - "8080:8080"
    depends_on:
      - maria-db

  maria-db:
    image: mariadb:10.4.8
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: remembrall
      MYSQL_USER: remembrall
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - maria-db-storage:/var/lib/mysql

volumes:
  maria-db-storage: